# Configuración básica del sitio
title: "LeoDAJM - GH"
description: "Personal GH Page"
author: "DAlejandroJM"

# URL del sitio
url: "https://leodajm.github.io/microsex/"
baseurl: "/microsex" # Deja vacío si es el repositorio principal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Configuraciones adicionales
markdown: kramdown
permalink: pretty # Define las URL amigables

# Configuración de la navegación
nav:
  - title: "Microsex Home Page"
    url: "/"
  - title: "Sobre mí"
    url: "/sobre.html"
  - title: "Contacto"
    url: "/contacto.html"

# Plugins a utilizar (si los necesitas)
plugins:
  - jekyll-feed # Para el RSS feed
  - jekyll-seo-tag # Para SEO

# Opciones de personalización
paginate: 5 # Número de entradas por página
exclude: # Archivos o directorios a excluir del sitio
  - README.md
  - LICENSE

# Parámetros adicionales (opcional)
social:
  github: "LeoDAJM"
