# Configuración básica del sitio
title: "LeoDAJM - GH"
description: "Personal GH Page"
author: "DAlejandroJM"

#remote_theme: b2a3e8/jekyll-theme-console
#heiswayi/thinkspace
#ankitsultana/researcher
#piharpi/jekyll-klise
#hydecorp/hydejack
#nielsenramon/chalk
#riggraz/no-style-please
#TolgaTatli/Moonrise/
remote_theme: TolgaTatli/Moonrise/
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Configuraciones adicionales
markdown: kramdown
permalink: pretty # Define las URL amigables
# Plugins a utilizar (si los necesitas)
plugins:
  - jekyll-feed # Para el RSS feed
  - jekyll-seo-tag # Para SEO

# Parámetros adicionales (opcional)
social:
  github: "LeoDAJM"
